# Generated by Django 6.0.1 on 2026-01-31 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="images/avatars/default.jpg",
                upload_to="images/avatars/%Y/%m/%d/",
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=("png", "jpg", "jpeg"))],
                verbose_name="Аватар",
            ),
        ),
    ]
