[project]
name = "blog-cbv"
version = "0.1.0"
description = ""
package-mode = false
authors = [
    {name = "k.barylnikov",email = "ipt_git_bot@ipt.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref (>=3.11.0,<4.0.0)",
    "django (>=6.0.1,<7.0.0)",
    "sqlparse (>=0.5.5,<0.6.0)",
    "pillow (>=12.1.0,<13.0.0)",
    "django-mptt (>=0.18.0,<0.19.0)",
    "django-mptt-admin (>=2.9.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.14.11,<0.15.0)"
]
