# Generated by Django 6.0.1 on 2026-02-05 17:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name="Краткое описание"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(verbose_name="Полный текст записи"),
        ),
    ]
